Repository LLNL/wcs, pull requests merged in 2020-07, with the labels that each got.

#11 Konsbr
  src/reaction.cpp
  src/reaction_network/network.cpp
  src/reaction_network/network.hpp
  src/reaction_network/vertex.cpp
  src/reaction_network/vertex.hpp
  src/utils/CMakeLists.txt
  src/utils/graph_factory.hpp
  src/utils/input_filetype.cpp
  src/utils/input_filetype.hpp
  src/utils/loadSBML.cpp
  src/utils/sbml_utils.cpp
  src/utils/sbml_utils.hpp
Labels: Review requesting, enhancement

#12 styling update
  src/bgl.hpp
  src/reaction_network/edge.cpp
  src/reaction_network/edge.hpp
  src/reaction_network/edge_weighted.cpp
  src/reaction_network/edge_weighted.hpp
  src/reaction_network/network.cpp
  src/reaction_network/network.hpp
  src/reaction_network/reaction.hpp
  src/reaction_network/reaction_base.cpp
  src/reaction_network/reaction_base.hpp
  src/reaction_network/reaction_impl.hpp
  src/reaction_network/species.cpp
  src/reaction_network/species.hpp
  src/reaction_network/vertex.cpp
  src/reaction_network/vertex.hpp
  src/reaction_network/vertex_flat.cpp
  src/reaction_network/vertex_flat.hpp
  src/reaction_network/vertex_property_base.cpp
  src/reaction_network/vertex_property_base.hpp
  src/utils/detect_methods.hpp
  src/utils/exception.cpp
  src/utils/exception.hpp
  src/utils/graph_factory.hpp
  src/utils/input_filetype.cpp
  src/utils/input_filetype.hpp
  src/utils/loadSBML.cpp
  src/utils/rngen.hpp
  src/utils/rngen_impl.hpp
  src/utils/sbml_utils.cpp
  src/utils/sbml_utils.hpp
  src/utils/seed.hpp
  src/utils/state_io.hpp
  src/utils/state_io_cereal.hpp
  src/utils/state_io_impl.hpp
  src/utils/streambuff.hpp
  src/utils/streambuff_impl.hpp
  src/utils/streamvec.hpp
  src/utils/streamvec_impl.hpp
  src/utils/timer.hpp
  src/utils/to_string.hpp
  src/utils/trace.cpp
  src/utils/trace.hpp
  src/utils/trace_ssa.cpp
  src/utils/trace_ssa.hpp
  src/utils/traits.hpp
  src/utils/write_graphviz.hpp
  src/utils/write_graphviz_impl.hpp
  src/wcs_types.hpp
Labels: styling

#15 Ongoing work for partitioning
  CMakeLists.txt
  src/partition.cpp
  src/reaction_network/edge_weighted.cpp
  src/reaction_network/edge_weighted.hpp
  src/reaction_network/vertex_flat.cpp
  src/utils/CMakeLists.txt
  src/utils/partition.cpp
  src/utils/partition.hpp
  src/utils/write_graphviz_impl.hpp
  src/wcs_types.hpp
Labels: enhancement

#18 Add cmake hook for ross
  CMakeLists.txt
  cmake/configure_files/WCSConfig.cmake.in
  cmake/configure_files/wcs_config.hpp.in
  cmake/configure_files/wcs_module.lua.in
  cmake/modules/FindROSS.cmake
  src/des.cpp
Labels: build

#17 Generate c code
  CMakeLists.txt
  src/utils/generate_cxx_code.cpp
Labels: Review requesting, enhancement
