Repository LLNL/wcs, pull requests merged in 2020-11, with the labels that each got.

#38 Index map
  src/reaction_network/network.cpp
  src/reaction_network/network.hpp
  src/sim_methods/sim_method.cpp
  src/sim_methods/sim_method.hpp
  src/sim_methods/ssa_direct.cpp
  src/sim_methods/ssa_direct.hpp
  src/sim_methods/ssa_nrm.cpp
  src/sim_methods/ssa_nrm.hpp
  src/sim_methods/ssa_sod.cpp
  src/sim_methods/ssa_sod.hpp
  src/ssa.cpp
  src/utils/samples_ssa.cpp
  src/utils/samples_ssa.hpp
  src/utils/trace_generic.cpp
  src/utils/trace_generic.hpp
  src/utils/trace_ssa.cpp
  src/utils/trace_ssa.hpp
  src/utils/trajectory.cpp
  src/utils/trajectory.hpp
  src/wcs_types.hpp
Labels: enhancement

#39 Schedule
  src/bgl.hpp
  src/sim_methods/sim_method.hpp
  src/sim_methods/sim_state_change.hpp
  src/sim_methods/ssa_direct.cpp
  src/sim_methods/ssa_direct.hpp
  src/sim_methods/ssa_nrm.cpp
  src/sim_methods/ssa_nrm.hpp
  src/sim_methods/ssa_sod.cpp
  src/sim_methods/ssa_sod.hpp
Labels: enhancement

#40 Remove the record of extra events occurred past the limit in trajectory
  src/sim_methods/sim_method.cpp
  src/utils/samples_ssa.cpp
  src/utils/samples_ssa.hpp
  src/utils/trace_generic.cpp
  src/utils/trace_generic.hpp
  src/utils/trace_ssa.cpp
  src/utils/trace_ssa.hpp
  src/utils/trajectory.hpp
Labels: enhancement

#41 Split ssa configuration out of ssa.cpp and put it into a separate header
  src/ssa-cfg.hpp
  src/ssa.cpp
Labels: enhancement

#33 Integrate generate cxx code to wcs
  CMakeLists.txt
  cmake/configure_files/wcs_config.hpp.in
  src/generate_cxx_code.cpp
  src/reaction_network/network.cpp
  src/reaction_network/reaction.hpp
  src/reaction_network/reaction_impl.hpp
  src/reaction_network/vertex.hpp
  src/utils/CMakeLists.txt
  src/utils/generate_cxx_code.cpp
  src/utils/generate_cxx_code.hpp
  src/utils/graph_factory.hpp
  src/utils/loadSBML.cpp
  tests/integration/ssa.sh
  tests/problem/Gillespie/eqn29-sbml.xml
Labels: enhancement

#42 Sequential DES for SSA
  CMakeLists.txt
  src/des.cpp
  src/des.hpp
  src/sim_methods/sim_method.hpp
  src/sim_methods/ssa_nrm.cpp
  src/sim_methods/ssa_nrm.hpp
  src/wcs-ross-bf.hpp
  tests/integration/ssa.sh
Labels: enhancement

#43 fix compilation error and cmake update to enforce the use of SBML and…
  CMakeLists.txt
  src/CMakeLists.txt
  src/sim_methods/ssa_nrm.cpp
  src/sim_methods/ssa_nrm.hpp
Labels: bug, build

#44 Enable a network object to represent a partition
  src/bgl.hpp
  src/partition.cpp
  src/partition/metis_partition.cpp
  src/partition/metis_partition.hpp
  src/reaction_network/network.cpp
  src/reaction_network/network.hpp
  src/reaction_network/vertex.cpp
  src/reaction_network/vertex.hpp
  src/reaction_network/vertex_flat.cpp
  src/reaction_network/vertex_flat.hpp
  src/sim_methods/ssa_nrm.cpp
  src/utils/write_graphviz.hpp
  src/utils/write_graphviz_impl.hpp
  src/wcs_types.hpp
Labels: enhancement

#45 README.md update
  README.md
Labels: documentation

#46 Count active reactions and report it when running `reaction`
  src/reaction.cpp
  src/reaction_network/network.cpp
  src/sim_methods/ssa_nrm.cpp
Labels: enhancement
