Repository LLNL/wcs, pull requests merged in 2021-02, with the labels that each got.

#56 Update the support for Intel compiler
  README.md
  cmake/modules/SetupCXX.cmake
  src/utils/samples_ssa.hpp
  src/utils/seed.hpp
  src/utils/trace_generic.hpp
  src/utils/trace_ssa.hpp
Labels: build

#62 relocate the routine to print the network content
  src/reaction.cpp
  src/reaction_network/network.cpp
  src/reaction_network/network.hpp
  src/sim_methods/sim_method.cpp
Labels: enhancement

#63 Fix the bug in termination condition check with NRM
  src/ssa-cfg.hpp
  src/wcs_types.hpp
Labels: bug

#61 Skip gen
  src/generate_cxx_code.cpp
  src/reaction_network/network.cpp
  src/reaction_network/network.hpp
  src/utils/file.cpp
  src/utils/file.hpp
  src/utils/generate_cxx_code.cpp
  src/utils/generate_cxx_code.hpp
  src/utils/graph_factory.hpp
  src/wcs_types.hpp
Labels: enhancement

#65 Add scripts to down-select species of interest in a trajectory result.
  scripts/trajectory/README.md
  scripts/trajectory/get_max_species.sh
  scripts/trajectory/get_max_species_list.awk
Labels: enhancement

#67 add cmake option to build WCS to support 64-bit species counter
  CMakeLists.txt
  cmake/configure_files/WCSConfig.cmake.in
  cmake/configure_files/wcs_config.hpp.in
  cmake/configure_files/wcs_module.lua.in
  src/reaction_network/network.cpp
  src/sim_methods/sim_method.cpp
  src/wcs_types.hpp
Labels: enhancement

#66 Fix the machine code generation for openmp.
  src/generate_cxx_code.cpp
Labels: bug

#72 Fix inputs of ExprTK
  src/reaction_network/reaction_impl.hpp
Labels: enhancement

#71 fix library path for dlopen
  src/utils/graph_factory.hpp
Labels: bug

#74 Change if condition value for denominators in generated code
  src/utils/generate_cxx_code.cpp
Labels: enhancement

#73 Generate codes into multiple translation units
  src/generate_cxx_code.cpp
  src/utils/generate_cxx_code.cpp
  src/utils/generate_cxx_code.hpp
Labels: enhancement

#80 add the brach missing in merging action
  src/utils/generate_cxx_code.cpp
Labels: bug

#83 README update
  CMakeLists.txt
  README.md
Labels: documentation

#85 add a utility function to create a directorty
  src/bgl.hpp
  src/utils/file.cpp
  src/utils/file.hpp
Labels: enhancement

#81 close the reaction function files
  src/utils/generate_cxx_code.cpp
  src/utils/generate_cxx_code.hpp
Labels: bug
