Repository LLNL/wcs, pull requests merged in 2021-03, with the labels that each got.

#58 Fix python script for generating mg_net networks.
  scripts/README.txt
  scripts/generate_network.py
  scripts/mg_net/README.md
  scripts/mg_net/generate_network.py
Labels: enhancement

#87 Fix bug in trajectory parsing. Allow users to choose either of the sp…
  scripts/trajectory/README.md
  scripts/trajectory/get_max_species.sh
  scripts/trajectory/get_max_species_list.awk
Labels: bug, enhancement

#88 bug fix for multi-translation unit JIT
  src/utils/file.cpp
  src/utils/file.hpp
  src/utils/generate_cxx_code.cpp
  src/utils/generate_cxx_code.hpp
Labels: bug

#89 Allow specifying different temporary directory in JIT
  src/generate_cxx_code.cpp
  src/reaction_network/network.cpp
  src/ssa_partition.cpp
  src/utils/generate_cxx_code.cpp
  src/utils/generate_cxx_code.hpp
Labels: enhancement

#91 Fix dep analysis with omp
  src/reaction_network/network.cpp
  src/reaction_network/network.hpp
  src/utils/generate_cxx_code.cpp
  src/utils/graph_factory.hpp
Labels: bug

#92 Fix a bug with the type of the input parameters in the script for mg_net
  scripts/mg_net/generate_network.py
Labels: bug

#93 remote duplicate lines
  src/utils/generate_cxx_code.cpp
Labels: bug

#94 Define CXX variable in makefile and replace hardcoded paths to the compiler
  src/utils/generate_cxx_code.cpp
Labels: enhancement

#96 Use variables to subsitute commonly used options in generated makefile
  src/utils/generate_cxx_code.cpp
Labels: enhancement

#97 use a relative path in the generated makefile
  src/utils/file.cpp
  src/utils/file.hpp
  src/utils/generate_cxx_code.cpp
Labels: enhancement

#98 Icc workaround
  src/utils/exception.hpp
Labels: bug

#99 Fix the type for exchanging vertex id between network partitions
  src/ssa_partition.cpp
Labels: bug, enhancement

#100 number of compiling treads in JIT
  src/generate_cxx_code.cpp
  src/utils/generate_cxx_code.cpp
  src/utils/generate_cxx_code.hpp
Labels: enhancement
